config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :actors
  resources :users
  resources :sessions
  resources :charges
  
  get "/logout", to: "sessions#destroy"
  root to: "movies#index"
end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_many :roles
  has_many :movies, through: :roles
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :movie
  belongs_to :genre
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :categorizations
  has_many :movies, through: :categorizations
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :studio
  has_many :roles
  has_many :actors, through: :roles
  has_many :categorizations
  has_many :genres, through: :categorizations
  validates :name, presence: true 

  def genres_text
    genres.collect { |genre| genre.name }.join(", ")    
  end  
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :movie
  belongs_to :actor
end

app/models/studio.rb
class Studio < ActiveRecord::Base
  has_many :movies
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  skip_before_action :authenticate, only: :show

  def index
    if current_user.role == 'admin'
      @actors = Actor.all
    else
      render text: "Sorry"
    end
  end
  
  def show
    @actor = Actor.find_by(id: params[:id])  
  end

  def new
    @actor = Actor.new
  end
  
  def create
    @actor = Actor.new
    @actor.name = params[:actor][:name]
    upload_photo
    @actor.save
    redirect_to actors_url
  end
  
  def edit
    @actor = Actor.find_by(id: params[:id])
  end
  
  def update
    @actor = Actor.find_by(id: params[:id])
    @actor.name = params[:actor][:name]
    upload_photo
    @actor.save
    redirect_to actors_url
  end
  
  def destroy
    @actor = Actor.find_by(id: params[:id])
    @actor.destroy
    redirect_to actors_url
  end

  def upload_photo
    # read the uploaded file
    file = params[:actor][:photo]
    if file.present?
      @actor.image = Base64.encode64(params[:actor][:photo].read)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate
  helper_method :current_user
  
  def authenticate
    if current_user.nil?
      render text: "Not authorized!!!"
      return
    end
  end
  
  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  skip_before_filter :authenticate

  def create
    # Amount in cents
    @amount = params[:amount]

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    redirect_to root_url, notice: "Thanks sucker!!!"
  rescue Stripe::CardError => e
    redirect_to new_charge_path, alert: e.message
  end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  
  def index
    @food = params[:food]
    @drink = params[:drink]
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  skip_before_action :authenticate, only: [:index, :show]
  
  def index
    if params[:genre_id]
      genre = Genre.find_by(id: params[:genre_id])
      @movies = genre.movies
    else
      @movies = Movie.all
    end
  end
  
  def show
    @movie = Movie.find_by(id: params[:id])
  end
  
  def new
    @movie = Movie.new
  end
  
  def create
    @movie = Movie.new
    omdb = OMDB.title(params[:movie][:name])
    @movie.name = omdb.title
    @movie.summary = omdb.plot
    @movie.rating = omdb.rated
    @movie.runtime = omdb.runtime
    @movie.year_released = omdb.year
    @movie.image = omdb.poster
    @movie.format = "Widescreen"
    @movie.save
    actor_names = omdb.actors.split(", ")
    actor_names.each do |actor_name|
      actor = Actor.find_or_create_by(name: actor_name)
      Role.create(movie: @movie, actor: actor)
    end
    genre_names = omdb.genre.split(", ")
    genre_names.each do |genre_name|
      genre = Genre.find_or_create_by(name: genre_name)
      Categorization.create(movie: @movie, genre: genre)
    end
    redirect_to movies_url
  end
  
  def edit
    @movie = Movie.find_by(id: params[:id])
  end
  
  def update
    @movie = Movie.find_by(id: params[:id])
    @movie.update(params[:movie])
    redirect_to movies_url
  end
  
  def destroy
    @movie = Movie.find_by(id: params[:id])
    @movie.destroy
    redirect_to movies_url
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate
  
  def create
    @user = User.find_by(email: params[:email])
    if @user.present?
      if @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to root_url, notice: "You're now logged-in"
      else
        redirect_to root_url, alert: "Invalid Password"
      end
    else
      redirect_to root_url, alert: "Nobody with that email address"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You're now logged-out"
  end
  
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create]

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.role = "user"
    @user.save
    if @user.valid?
      redirect_to users_path, notice: "Yay!!!"
    else
      render "new"
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.update(params[:user])
    redirect_to users_path
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    redirect_to users_path
  end

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actors/_form.html.erb
<%= bootstrap_form_for @actor do |form| %>
  <%= form.text_field :name %>
  <%= form.file_field :photo %>
  <%= form.button 'Save Actor', class: "btn btn-success" %>
<% end %>

app/views/actors/edit.html.erb
<%= render 'form' %>

app/views/actors/index.html.erb
<h3 class="page-header">
  All Actors
  <span class="pull-right">
    <%= link_to "New Actor", new_actor_url, class: 'btn btn-sm btn-success' %>
  </span>
</h3>

<ul>
  <% @actors.each do |actor| %>
    <li>
      <%= link_to actor.name, actor %>
      <%= link_to "Edit", edit_actor_url(actor) %>
      <%= link_to "Delete", 
            actor_url(actor), 
            method: :delete,
            data: { confirm: 'No, really?!' } %>
    </li>
  <% end %>
</ul>

app/views/actors/new.html.erb
<%= render 'form' %>

app/views/actors/show.html.erb
<% if @actor.image.present? %>
  <%= image_tag "data:image/*;base64,#{@actor.image}" %> 
<% end %>

<h3><%= @actor.name %></h3>

<div class="row">

  <% @actor.movies.each do |m| %>

    <%= render "shared/movie", movie: m %>  

  <% end %>

</div>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>

  <article>
    <label class="amount">
      <span>Amount: $25.00</span>
    </label>
  </article>

  <%= hidden_field_tag :amount, 2500 %>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Superman III"
          data-amount="2500"></script>

<% end %>

app/views/hello/index.html.erb
<h1>Hello, you love <%= @food %> and <%= @drink %>!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Buyflix</title>

  <!-- Logo Font -->
  <link href="//fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet" type="text/css">

  <!-- My JavaScript -->
  <%= javascript_include_tag 'application' %>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  
  <!-- Bootstrap JavaScript -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <!-- Highcharts -->
  <script src="http://code.highcharts.com/highcharts.js"></script>

  <!-- My own CSS -->
  <%= stylesheet_link_tag    'application', media: 'all' %>

  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger"><%= alert %></div>
    <% end %>

    <nav class="navbar navbar-inverse" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <!-- Rails equivalent to -->
        <!-- <a href="/" class="navbar-brand">Buyflix</a> -->
        <%= link_to "Buyflix", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <a href="/">
              <i class="fa fa-home"></i>
              Home
            </a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              Genres
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <% Genre.order(:name).each do |genre| %>
                <li><%= link_to genre.name, movies_url(genre_id: genre.id) %></li>
              <% end %>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <% if current_user.role == "admin" %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                  <i class="fa fa-cog"></i>
                  Admin
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Actors", actors_path %></li>
                  <li><%= link_to "Users", users_path %></li>
                  <li><%= link_to "New Movie", new_movie_path %></li>
                </ul>
              </li>
            <% end %>
            <li><%= link_to "Welcome " + current_user.name %></li>
            <li><%= link_to "Sign Out", logout_url %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_url %></li>
            <li><%= link_to "Sign In", new_session_url %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/movies/edit.html.erb
<%= bootstrap_form_for @movie do |form| %>
  <%= form.text_field :name %>
  <%= form.text_field :image %>
  <%= form.text_area :summary %>
  <%= form.text_field :year_released %>
  <%= form.text_field :rating %>
  <%= form.text_field :genre %>
  <%= form.text_field :runtime %>
  <%= form.text_field :format %>
  <%= form.text_field :price %>
  <%= form.collection_select :studio_id, Studio.all, :id, :name %>
  <%= form.collection_check_boxes :actor_ids, Actor.all, :id, :name %>
  <%= form.button 'Save Movie', class: "btn btn-success" %>
<% end %>

app/views/movies/index.html.erb
<div class="row">
  <% @movies.each do |m| %>
    <%= render "shared/movie", movie: m %>
  <% end %>
</div>

<script>
  $(function () { 
    $('#chart').highcharts({
      chart: {
        type: 'column'
      },
      title: {
        text: 'Movie Runtime, 2015'
      },
      xAxis: {
        categories: ['Runtime']
      },
      yAxis: {
        title: {
          text: 'Minutes'
        }
      },
      legend: {
        enabled: false
      },
      plotOptions: {
        column: {
          groupPadding: 1.0
        }
      },
      series: [
        {
          name: 'Jane',
          data: [1, 0, 4]
        }, 
        {
          name: 'John',
          data: [5, 7, 3]
        }
      ]
    });
  });
</script>

app/views/movies/new.html.erb
<%= bootstrap_form_for @movie do |form| %>
  <%= form.text_field :name %>
  <%= form.button 'Create Movie', class: "btn btn-success" %>
<% end %>

app/views/movies/show.html.erb
<!-- Use view helpers (e.g. link_to and image_tag) -->
<!-- and implement real data -->

<h1 class="title">
  <%= @movie.name %>
  <span class="rating"><%= @movie.rating %></span>
</h1>

<div class="row">
  <div class="col-md-3 text-center">
    <p><%= image_tag @movie.image %></p>
    <p><a href="#" class="btn btn-sm btn-success"><i class="fa fa-shopping-cart"></i> $<%= @movie.price.to_f / 100 %> Buy in HD</a></p>
    <p><strong>Genre:</strong> <%= @movie.genres_text %></p>
    <p><strong>Released:</strong> <%= @movie.year_released %></p>
  </div>
  <div class="col-md-4 summary">
    <h2>Summary</h2>
    <p>
      <%= @movie.summary %>
    </p>
  </div>
  <div class="col-md-3 actors">
    <h2>Cast</h2>
    <ul class="list-unstyled">
      <% @movie.roles.each do |role| %>
        <% if role.actor.present? %>
          <% if role.character_name.present? %>
            <li><%= link_to role.actor.name, role.actor %> as <%= role.character_name %></li>
          <% else %>
            <li><%= link_to role.actor.name, role.actor %></li>
          <% end %>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col-md-9 col-md-offset-3 reviews">
    <h2 class="page-header">Information</h2>
    <table class="table table-striped table-bordered">
      <tr>
        <td><strong>Studio</strong></td>
        <td><%= @movie.studio.try(:name) %></td>
      </tr>
      <tr>
        <td><strong>Run Time</strong></td>
        <td><%= @movie.runtime %></td>
      </tr>
    </table>
  </div>
</div>

app/views/shared/_movie.html.erb
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">
    <%= link_to image_tag(movie.image), movie_url(movie) %>
    <div class="caption">
      <h3><%= link_to movie.name, movie_url(movie) %></h3>
      <p><%= movie.summary %></p>
      <% if current_user && current_user.role == "admin" %>
        <p>
          <%= link_to "Edit", edit_movie_path(movie), class: "btn btn-default" %>
          <%= link_to "Delete", movie_path(movie), 
                method: :delete, 
                class: "btn btn-danger",
                data: { confirm: "Really?" } %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= bootstrap_form_for @user do |form| %>
  <%= form.text_field :email %>
  <%= form.password_field :password %>
  <%= form.text_field :name %>
  <%= form.select :role, ["admin", "user"] %>
  <%= form.button 'Update User', class: "btn btn-success" %>
<% end %>

app/views/users/index.html.erb
<h3 class="page-header">
  All Users
  <span class="pull-right">
    <%= link_to "New User", new_user_path, class: 'btn btn-sm btn-success' %>
  </span>
</h3>

<ul>
  <% @users.each do |user| %>
    <li><%= user.name %> <%= link_to "Edit", edit_user_path(user) %> <%= link_to "Delete", user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<%= bootstrap_form_for @user do |form| %>
  <%= form.text_field :email %>
  <%= form.password_field :password %>
  <%= form.password_field :password_confirmation %>
  <%= form.text_field :name %>
  <%= form.button 'Sign Up', class: "btn btn-success" %>
<% end %>